# _    _                    _____ _ _     _
# | |  | |                  / ____| (_)   | |
# | |__| | __ _ _ __   __ _| |  __| |_  __| | ___ _ __
# |  __  |/ _` | '_ \ / _` | | |_ | | |/ _` |/ _ \ '__|
# | |  | | (_| | | | | (_| | |__| | | | (_| |  __/ |
# |_|__|_|\__,_|_| |_|\__, |\_____|_|_|\__,_|\___|_|      __ ___
# |  _ \            /\ __/ | | |            | |          /_ |__ \
# | |_) |_   _     /  \___/__| |__   ___  __| | ___  _ __ | |  ) |
# |  _ <| | | |   / /\ \ / __| '_ \ / _ \/ _` |/ _ \| '_ \| | / /
# | |_) | |_| |  / ____ \ (__| | | |  __/ (_| | (_) | | | | |/ /_
# |____/ \__, | /_/    \_\___|_| |_|\___|\__,_|\___/|_| |_|_|____|
#         __/ |
#        |___/

# Plugin Version | do not touch this
version: v1.0

# This feature is not yet configurable
HangGlider: 341

# Set your favorite Language <FR | ENG | ESP>
# Coming soon

Language: FR
